The sanitizer detected a data race vulnerability. The explanation of the vulnerability is: A data race occurred, indicating a potential issue in the code or environment. Here is the detail: 

  Read of size 8 at 0x7fadbc570760 by thread T1391:
    - PyMember_GetOne /home/realkumaraditya/cpython/Python/structmember.c:88:13
    - member_get /home/realkumaraditya/cpython/Objects/descrobject.c:180:12
    - PyObject_GenericGetAttr /home/realkumaraditya/cpython/Objects/object.c:1792:12
    - PyObject_GetAttr /home/realkumaraditya/cpython/Objects/object.c:1296:18
    - _PyEval_EvalFrameDefault /home/realkumaraditya/cpython/Python/generated_cases.c.h:7710:30
    - _PyEval_EvalFrame /home/realkumaraditya/cpython/Include/internal/pycore_ceval.h:119:16
    - _PyEval_Vector /home/realkumaraditya/cpython/Python/ceval.c:1917:12
    - PyEval_EvalCode /home/realkumaraditya/cpython/Python/ceval.c:829:21
    - builtin_exec_impl /home/realkumaraditya/cpython/Python/bltinmodule.c:1158:17
    - builtin_exec /home/realkumaraditya/cpython/Python/clinic/bltinmodule.c.h:568:20
    - _PyEval_EvalFrameDefault /home/realkumaraditya/cpython/Python/generated_cases.c.h:2179:35
    - _PyEval_EvalFrame /home/realkumaraditya/cpython/Include/internal/pycore_ceval.h:119:16
    - _PyEval_Vector /home/realkumaraditya/cpython/Python/ceval.c:1917:12
    - _PyObject_VectorcallTstate /home/realkumaraditya/cpython/Include/internal/pycore_call.h:169:11
    - method_vectorcall /home/realkumaraditya/cpython/Objects/classobject.c:94:18
    - _PyVectorcall_Call /home/realkumaraditya/cpython/Objects/call.c:273:16
    - _PyObject_Call /home/realkumaraditya/cpython/Objects/call.c:348:16
    - PyObject_Call /home/realkumaraditya/cpython/Objects/call.c:373:12
    - _PyEval_EvalFrameDefault /home/realkumaraditya/cpython/Python/generated_cases.c.h:2448:32
    - _PyEval_EvalFrame /home/realkumaraditya/cpython/Include/internal/pycore_ceval.h:119:16
    - _PyEval_Vector /home/realkumaraditya/cpython/Python/ceval.c:1917:12
    - _PyObject_VectorcallTstate /home/realkumaraditya/cpython/Include/internal/pycore_call.h:169:11
    - method_vectorcall /home/realkumaraditya/cpython/Objects/classobject.c:72:20
    - _PyObject_VectorcallTstate /home/realkumaraditya/cpython/Include/internal/pycore_call.h:169:11
    - context_run /home/realkumaraditya/cpython/Python/context.c:728:29
    - _PyEval_EvalFrameDefault /home/realkumaraditya/cpython/Python/generated_cases.c.h:3507:35
    - _PyEval_EvalFrame /home/realkumaraditya/cpython/Include/internal/pycore_ceval.h:119:16
    - _PyEval_Vector /home/realkumaraditya/cpython/Python/ceval.c:1917:12
    - _PyObject_VectorcallTstate /home/realkumaraditya/cpython/Include/internal/pycore_call.h:169:11
    - method_vectorcall /home/realkumaraditya/cpython/Objects/classobject.c:72:20
    - _PyVectorcall_Call /home/realkumaraditya/cpython/Objects/call.c:273:16
    - _PyObject_Call /home/realkumaraditya/cpython/Objects/call.c:348:16
    - PyObject_Call /home/realkumaraditya/cpython/Objects/call.c:373:12
    - thread_run /home/realkumaraditya/cpython/Modules/_threadmodule.c:353:21
    - pythread_wrapper /home/realkumaraditya/cpython/Python/thread_pthread.h:242:5

  Previous write of size 8 at 0x7fadbc570760 by thread T1392:
    - PyCData_GetContainer /home/realkumaraditya/cpython/Modules/_ctypes/_ctypes.c:2840:29
    - KeepRef_lock_held /home/realkumaraditya/cpython/Modules/_ctypes/_ctypes.c:2900:10
    - KeepRef /home/realkumaraditya/cpython/Modules/_ctypes/_ctypes.c:2943:11
    - PyCData_set /home/realkumaraditya/cpython/Modules/_ctypes/_ctypes.c:3505:12
    - Array_ass_item_lock_held /home/realkumaraditya/cpython/Modules/_ctypes/_ctypes.c:5094:12
    - Array_ass_subscript_lock_held /home/realkumaraditya/cpython/Modules/_ctypes/_ctypes.c:5127:16
    - Array_ass_subscript /home/realkumaraditya/cpython/Modules/_ctypes/_ctypes.c:5171:14
    - PyObject_SetItem /home/realkumaraditya/cpython/Objects/abstract.c:235:19
    - _PyEval_EvalFrameDefault /home/realkumaraditya/cpython/Python/generated_cases.c.h:11172:27
    - _PyEval_EvalFrame /home/realkumaraditya/cpython/Include/internal/pycore_ceval.h:119:16
    - _PyEval_Vector /home/realkumaraditya/cpython/Python/ceval.c:1917:12
    - PyEval_EvalCode /home/realkumaraditya/cpython/Python/ceval.c:829:21
    - builtin_exec_impl /home/realkumaraditya/cpython/Python/bltinmodule.c:1158:17
    - builtin_exec /home/realkumaraditya/cpython/Python/clinic/bltinmodule.c.h:568:20
    - _PyEval_EvalFrameDefault /home/realkumaraditya/cpython/Python/generated_cases.c.h:2179:35
    - _PyEval_EvalFrame /home/realkumaraditya/cpython/Include/internal/pycore_ceval.h:119:16
    - _PyEval_Vector /home/realkumaraditya/cpython/Python/ceval.c:1917:12
    - _PyObject_VectorcallTstate /home/realkumaraditya/cpython/Include/internal/pycore_call.h:169:11
    - method_vectorcall /home/realkumaraditya/cpython/Objects/classobject.c:94:18
    - _PyVectorcall_Call /home/realkumaraditya/cpython/Objects/call.c:273:16
    - _PyObject_Call /home/realkumaraditya/cpython/Objects/call.c:348:16
    - PyObject_Call /home/realkumaraditya/cpython/Objects/call.c:373:12
    - _PyEval_EvalFrameDefault /home/realkumaraditya/cpython/Python/generated_cases.c.h:2448:32
    - _PyEval_EvalFrame /home/realkumaraditya/cpython/Include/internal/pycore_ceval.h:119:16
    - _PyEval_Vector /home/realkumaraditya/cpython/Python/ceval.c:1917:12
    - _PyObject_VectorcallTstate /home/realkumaraditya/cpython/Include/internal/pycore_call.h:169:11
    - method_vectorcall /home/realkumaraditya/cpython/Objects/classobject.c:72:20
    - _PyObject_VectorcallTstate /home/realkumaraditya/cpython/Include/internal/pycore_call.h:169:11
    - context_run /home/realkumaraditya/cpython/Python/context.c:728:29
    - _PyEval_EvalFrameDefault /home/realkumaraditya/cpython/Python/generated_cases.c.h:3507:35
    - _PyEval_EvalFrame /home/realkumaraditya/cpython/Include/internal/pycore_ceval.h:119:16
    - _PyEval_Vector /home/realkumaraditya/cpython/Python/ceval.c:1917:12
    - _PyObject_VectorcallTstate /home/realkumaraditya/cpython/Include/internal/pycore_call.h:169:11
    - method_vectorcall /home/realkumaraditya/cpython/Objects/classobject.c:72:20
    - _PyVectorcall_Call /home/realkumaraditya/cpython/Objects/call.c:273:16
    - _PyObject_Call /home/realkumaraditya/cpython/Objects/call.c:348:16
    - PyObject_Call /home/realkumaraditya/cpython/Objects/call.c:373:12
    - thread_run /home/realkumaraditya/cpython/Modules/_threadmodule.c:353:21
    - pythread_wrapper /home/realkumaraditya/cpython/Python/thread_pthread.h:242:5


To fix this issue, follow the advice below:

1. Review the code for potential data races and correct them.
2. Check for concurrent access to shared resources.
3. Implement synchronization mechanisms to prevent data races.